import JSZip from "jszip";
import type { GeneratedFile, LearningPath, Plan, Project } from "@/lib/schemas";
import { buildPackageJson } from "@/lib/validate/build";

export function generateLearningGuideMd(project: Project): string {
  const lp = project.learningPath;
  if (!lp) {
    return `# Learning Guide: ${project.title}\n\nRun the Learn stage in Valor AppStudio to generate this comprehensive guide!`;
  }

  const conceptsSection = lp.concepts
    .map(
      (c) => `### ${c.name}\n**Found in**: \`${c.file}\`\n\n${c.definition}\n\n\`\`\`javascript\n${c.snippet}\n\`\`\``
    )
    .join("\n\n");

  const lessonsSection = lp.lessons
    .map((l, i) => {
      const steps = l.steps.map((s) => `1. ${s}`).join("\n");
      const hints = l.exercise.hints.map((h) => `- *Hint*: ${h}`).join("\n");
      return `## Lesson ${i + 1}: ${l.title}\n**Goal**: ${l.goal}\n**Files involved**: ${l.files.map((f) => `\`${f}\``).join(", ")}\n\n### Steps to Rebuild\n${steps}\n\n### Hands-On Exercise\n${l.exercise.prompt}\n\n${hints}\n\n**Expected Outcome**: ${l.exercise.expectedOutcome}`;
    })
    .join("\n\n---\n\n");

  const quizSection = lp.quiz
    .map((q, i) => {
      const opts = q.options.map((opt, oi) => `  ${String.fromCharCode(65 + oi)}) ${opt}`).join("\n");
      const answerLetter = String.fromCharCode(65 + q.answerIndex);
      return `#### Question ${i + 1}: ${q.question}\n${opts}\n\n> **Correct Answer**: ${answerLetter}\n> *Explanation*: ${q.explanation}`;
    })
    .join("\n\n");

  return `# ${project.title} — Comprehensive Learning Guide
Generated by **Valor AppStudio** (Learn Stage)

---

## 1. Core Concepts Used in this Project
${conceptsSection}

---

## 2. Step-by-Step Rebuild Curriculum
${lessonsSection}

---

## 3. Knowledge Check Quiz (5 Questions)
${quizSection}

---

## 4. Recommended Next Steps & Resources
${lp.nextSteps.map((ns) => `- **[${ns.title}](${ns.url})**: ${ns.description}`).join("\n")}
`;
}

export async function exportProjectZip(project: Project): Promise<Blob> {
  const zip = new JSZip();

  // Package.json auto-fix / addition
  const hasPkg = project.files.some((f) => f.path === "package.json");
  const files: GeneratedFile[] = [...project.files];
  if (!hasPkg) {
    files.push(buildPackageJson(project.brief?.appName || project.title, files));
  }

  // Add all files
  for (const f of files) {
    zip.file(f.path, f.content);
  }

  // Add LEARNING_GUIDE.md if learning path exists
  zip.file("LEARNING_GUIDE.md", generateLearningGuideMd(project));

  return await zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
